---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: raven-nest
# description will be included in the image's metadata
description: "Raven - Simplified Bazzite-Gnome for AMD desktop."
# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - starship
    remove:
      - webapp-manager
      - tailscale
      - sunshine
      # Remote desktop and VNC.
      - gnome-remote-desktop
      - libvncserver
      # Accessability
      - orca
      - speech-dispatcher
      - speech-dispatcher-espeak-ng
      - espeak-ng
      # Android
      - android-udev-rules
      - waydroid
      - waydroid-selinux
      # Fonts for languages other that English.
      - default-fonts-am
      - default-fonts-ar
      - default-fonts-as
      - default-fonts-ast
      - default-fonts-be
      - default-fonts-bg
      - default-fonts-bn
      - default-fonts-bo
      - default-fonts-br
      - default-fonts-chr
      - default-fonts-cjk-mono
      - default-fonts-cjk-serif
      - default-fonts-dv
      - default-fonts-dz
      - default-fonts-el
      - default-fonts-eo
      - default-fonts-eu
      - default-fonts-fa
      - default-fonts-gu
      - default-fonts-he
      - default-fonts-hi
      - default-fonts-hy
      - default-fonts-ia
      - default-fonts-iu
      - default-fonts-ka
      - default-fonts-km
      - default-fonts-kn
      - default-fonts-ku
      - default-fonts-lo
      - default-fonts-mai
      - default-fonts-ml
      - default-fonts-mni
      - default-fonts-mr
      - default-fonts-my
      - default-fonts-nb
      - default-fonts-ne
      - default-fonts-nn
      - default-fonts-nr
      - default-fonts-nso
      - default-fonts-or
      - default-fonts-other-mono
      - default-fonts-other-sans
      - default-fonts-other-serif
      - default-fonts-pa
      - default-fonts-ru
      - default-fonts-sat
      - default-fonts-si
      - default-fonts-ss
      - default-fonts-ta
      - default-fonts-te
      - default-fonts-th
      - default-fonts-tn
      - default-fonts-ts
      - default-fonts-uk
      - default-fonts-ur
      - default-fonts-ve
      - default-fonts-vi
      - default-fonts-xh
      - default-fonts-yi
      - default-fonts-zu
      - google-noto-sans-arabic-vf-fonts
      - google-noto-naskh-arabic-vf-fonts
      - google-noto-sans-armenian-vf-fonts
      - google-noto-sans-balinese-fonts
      - google-noto-sans-bengali-vf-fonts
      - google-noto-sans-canadian-aboriginal-vf-fonts
      - google-noto-sans-cherokee-vf-fonts
      - google-noto-sans-cjk-fonts
      - google-noto-sans-devanagari-vf-fonts
      - google-noto-sans-ethiopic-vf-fonts
      - google-noto-sans-georgian-vf-fonts
      - google-noto-sans-gujarati-vf-fonts
      - google-noto-sans-gurmukhi-vf-fonts
      - google-noto-sans-hebrew-vf-fonts
      - google-noto-sans-javanese-fonts
      - google-noto-sans-kannada-vf-fonts
      - google-noto-sans-khmer-vf-fonts
      - google-noto-sans-lao-vf-fonts
      - google-noto-sans-meetei-mayek-vf-fonts
      - google-noto-sans-mono-cjk-vf-fonts
      - google-noto-sans-ol-chiki-vf-fonts
      - google-noto-sans-oriya-vf-fonts
      - google-noto-sans-sinhala-vf-fonts
      - google-noto-sans-sundanese-fonts
      - google-noto-sans-tamil-vf-fonts
      - google-noto-sans-telugu-vf-fonts
      - google-noto-sans-thaana-vf-fonts
      - google-noto-sans-thai-vf-fonts
      
  - type: default-flatpaks
    notify: true
    system: # Default Flathub
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.spotify.Client
        - com.discordapp.Discord
      remove:
        - org.gnome.eog
    user: {}

  - type: signing

